language: java
sudo: false
jdk:
  - oraclejdk8
before_install:
- wget -P /tmp http://www.apache.org/dist/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.zip
- unzip -d /tmp -qq /tmp/apache-maven-3.3.9-bin.zip
- export M2_HOME=tmp/apache-maven-3.3.9
- chmod +x $M2_HOME/bin/mvn
- export PATH=$M2_HOME/bin:$PATH
- pip install --user codecov
install: true
script:
- mvn clean install
after_success:
  - bash <(curl -s https://codecov.io/bash)
before_deploy:
- pip install --user requests
deploy:
  provider: script
  script: mvn deploy
cache:
  directories:
  - "$HOME/.m2"
env:
  global:
  - secure: "aott9rBOsupYRzxSByLpD4HkcNYKAFWzPpnsKHY+VgYmYbSODhX8/PiyARJtx386nqkbfm7PzbhmmpR9YV77u75PPd6w0MBJJT00DAS2Mx+P70NGMqLZGqOe9wVlgoQgZATQZCuUasZ+nXylaF+fj9AXqQsQN5JphkVVPyOUOcC8MAZ0VXuCafZ2kNwguYXy+16oy6RFB2JOQxPCY56U3dghxLI5YXftfG2BL5kEZQ8air9+j9u5pBxnYAyryR0m3tuJrwB2oEwCbiQMtc4SqiFcfbcoss9Cvy04f0Q2o/w2aNspcagnqlWtAh4cGo5NFpAlrh6WkzCm/U3PDdTYERbFJLb/pZKxx6Qzu0QuKa691tmJr2/Bqi/HbtzvY0vGyJyL2qtx8aRLVzRTjwNTLXHUHUCGzp8uGHtK5qi81pDQVSjZahY9IL8/WO9DO4w2U0pxYUncGK0fXg+Nk/mXqjcV54IkhDr8ewIV5UFVEZaYEd8mCd6pxbczuajU3fpoerI6fGCWeNv3kqcxR8jp5S9aBdnzLf4TLAs2zFjsluTkh0ZV/HsIZvyfqOdosa1mXVkRpCWF72uiPHvcRHTl6qHmp5Li/F9CMwO1fKc7SSDoe+mzRAPvgG09ImuL/MiogwGdQvPdWIjh7KlvTouDSPq15SDGBJbFI+7AcZ0hoIU="
  - secure: "MAs4wUEirGkqeaJk7pxDgb8f/FNLU5JUs+ukdtQltdhOa52eR+6kgTsCM4azvW/gAny28q0+Aiql4LgVyUZiCPTQdiPN69LSC3xEVLyk4Hno24RJdoPYw4liVSwYsg3L8H+RA/LB7wAlWUxdiJ3eFXIqgo6wiwfgvc60pz8c9476q0M//R4qRTDyhS3/7dZNoNoZzCwwqwbKXeMhD07uJiyeYLoNEoPz6xZhCBTaGx0R6xZEPpwMByrJ+7gVQ8C939519x2TyWgp6YmQXhnoHZy2wUYW/B9nQAm86pZ9MLb+qPPTe+/Q9j4XeIjUb54kpQBsxtlhGV1ZxsdT/MkspslVh515TeC72JTJ8edL56ZHqHEawlfrCLTtHnWi2mBQl8uY/d4klRQQqZpI0LThCDTIogGQfgJAADTybnbwRTYC75WwmoCK4IqCqBzRXg2RnCVRyyYbXN0t8df80ZzDCOBZb7t1FO2has2DiziQ1MCqqKjVP3ZK6ZRMHtcU9pZ7TWZEY3gMZ3YApVJZYOtqFO6ToERCY+rz2t03cnMDasKeyeEIuBFPL1bbhuHt1lydwEd3aJPS+OrlaQxp2Xk4lu7DEvMraF6SLtWoGM25cED1b05bKMYdcR0rSCUp3rvlnczPuyobazKQ/Gm0UAOPtoWRHG+ur288i6h7F17cMYE="
